# Generated by Django 2.2.6 on 2021-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210129_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для своего поста.', null=True, upload_to='posts/', verbose_name='Изображение:'),
        ),
    ]
